### ISSUE TITLE
protoc-gen-gopherjs: Use webpack to resolve imports after generation

### ISSUE THREAD

**Issue by johanbrandhorst** [johanbrandhorst/protobuf#11]
This could remove the ugly sed replacing that's currently in-use.

See https://www.marwan.io/blog/wrapping-node-modules-with-gopherjs for some ideas.

**Comment by johanbrandhorst** [comment]
Fixed in master, updated protoc-gen-gopherjs README with tips for adopter.

**Comment by norunners** [comment]
Got a reference to the commit?

**Comment by johanbrandhorst** [comment]
https://github.com/johanbrandhorst/protobuf/commit/17192d4c1319852148d575b002786bec9f1e08c1
https://github.com/johanbrandhorst/protobuf/commit/374a20a9b021aeca05863acd5f23907aff5584ad

From a user point of view it's probably easier to look at the grpcweb-example repo:
https://github.com/johanbrandhorst/grpcweb-example/commit/5caf1d67b220ec3b2b2cb5400346362327b5f1b4
