### ISSUE TITLE
Idea: Hack in support for bidirectional streaming with websockets

### ISSUE THREAD

**Issue by johanbrandhorst** [johanbrandhorst/protobuf#16]
It should be possible to implement a gRPC like interface for writing and reading form a websocket as if it was a bidirectional streaming endpoint.

**Comment by johanbrandhorst** [comment]
I'm thinking something along the lines of https://github.com/tmc/grpc-websocket-proxy but adapted for binary streaming rather than newline delimited JSON messages.

**Comment by johanbrandhorst** [comment]
It kind of works 💯

**Comment by joeblew99** [comment]
This is great..

**Comment by johanbrandhorst** [comment]
Made some more progress on this so far this weekend, hoping to have a first version ready tomorrow :)

**Comment by joeblew99** [comment]
thanks for updating us. This is very useful stuff.
Really looking forward giving it a whirl....

**Comment by joeblew99** [comment]
I also mentioned this to myitcv, but there is a good CRDT lib now that is written in JS but i am looking to port to golang. The author also wants to port to golang.
Its useful fro network partitions of course. 

here is the link. 
https://github.com/y-js/yjs

**Comment by johanbrandhorst** [comment]
You can check out the progress in #18, I'm still tweaking it a little bit.

**Comment by joeblew99** [comment]
This is insanely useful .. Will be tire kicking :)
