### ISSUE TITLE
Generated proto file has wrong imports

### ISSUE THREAD

**Issue by mwei0210** [johanbrandhorst/protobuf#34]
```
import google_protobuf "google/protobuf"
import google_protobuf1 "google/protobuf"
import google_protobuf2 "google/protobuf"
```
instead of protoc:
```
import any "github.com/golang/protobuf/ptypes/any"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
```

**Comment by johanbrandhorst** [comment]
Hi! Thanks for raising an issue. Could you show me the `.proto` file you used and the `protoc` command used? This doesn't look like it should be happening.

**Comment by mwei0210** [comment]
Hi @johanbrandhorst , this would generate an instance of  `import google_protobuf "google/protobuf"`
```
syntax = "proto3";

package account;

import "google/protobuf/any.proto";

message Account {
    google.protobuf.Any metadata = 4;
}
```

**Comment by mwei0210** [comment]
ah it works now thanks! Is there anyway to automate it?

**Comment by johanbrandhorst** [comment]
Unfortunately this `M`-parameter always has to be supplied to `protoc` since the source file you're using declares `go_package = github.com/golang/protobuf/ptypes/any`. Glad it fixed your use case though!
