### ISSUE TITLE
Unable to run simple gopherjs demo with protoc compiled grpc-web

### ISSUE THREAD

**Issue by softkot** [johanbrandhorst/protobuf#45]
After opening the page nothing happens except console error:

```
web.js:2535 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at new Map (web.js:2535:46842)
    at $internalize (web.js:2049:36)
    at init (gopherjs__runtime.go:78:3)
    at Object.$init (web.js:2528:3)
    at web.js:3623:22
    at web.js:3627:4
```

The steps to reproduce:

```
git clone https://gitlab.com/softkot/gopher_grpc_web.git
cd gopher_grpc_web
make init
make proto
make serve
```

after seenig 
```
alias go="go1.17.9"
export GOPHERJS_GOROOT=/home/kot/sdk/go1.17.9
gopherjs serve gitlab.com/softkot/gopher_grpc_web
serving at http://localhost:8080 and on port 8080 of any available addresses
```

open http://localhost:8080 and enable developer mode on browser. Navigate to console.

![image](https://github.com/johanbrandhorst/protobuf/assets/5500358/805da713-378f-4ef4-b382-41ef235a1815)

P.S.

gopherjs cersion v1.17.2
go version 1.17.9
protoc-gen-gopherjs virsion v0.7.1

Other combinations produce the same results

**Comment by johanbrandhorst** [comment]
Hi! It doesn't surprise me that this has bitrotten a bit. I haven't updated it in **checks notes** _6 years_. Unfortunately this project isn't that important to me anymore. I would recommend investing time in using a project like https://connect.build instead.
